sudo: required

language: minimal

services:
- docker

before_install:
- docker-compose -f docker/build/docker-compose.yml build

script:
- docker-compose -f docker/build/docker-compose.yml run build script/test.sh

env:
  - DEVISE_SECRET_KEY='-- secret string --'
  - SECRET_TOKEN='-- secret string --'
  - STRIPE_API_KEY='REPLACE'
  - STRIPE_API_PUBLIC='REPLACE'
  - S3_BUCKET_NAME='REPLACE'
  - AWS_ACCESS_KEY='REPLACE'
  - AWS_SECRET_ACCESS_KEY='REPLACE'
