sudo: required

language: ruby

services:
- docker

before_install:
- docker-compose -f docker/build/docker-compose.yml build

script:
- docker-compose -f docker/build/docker-compose.yml run build script/test.sh