sudo: required

language: minimal

services:
- docker

before_install:
- docker-compose -f docker/build/docker-compose.yml build
- cp .env.template .env

script:
- docker-compose -f docker/build/docker-compose.yml -e RACK_ENV=ci -e RAILS_ENV=ci run build script/test.sh