# License: CC0-1.0
version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      args:
        - USER
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
      - memcached
    user: ${USER}
    environment:
      - USER=${USER}
      - DATABASE_HOST=db
      - MEMCACHE_SERVERS=memcached
  memcached:
    image: memcached
