# License: LGPL-3.0-or-later
name: NOTICE-ruby verification
on: 
  pull_request_target:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
env:
  os: ubuntu-20.04
  ruby: '2.7.4'
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - name: run notice:ruby:verify
        run: |
            bin/rails notice:ruby:verify
      - name: output the branch
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        run: | 
          echo ${{ github.ref }}
      - name: run notice:ruby:update
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        run: |
            bin/rails notice:ruby:update
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add NOTICE-ruby
            git commit -m "Updated NOTICE-ruby"
            git push
