# License: LGPL-3.0-or-later
name: NOTICE-ruby verification
on: 
  push:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
  pull_request:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
env:
  os: ubuntu-20.04
  ruby: '2.7.4'
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - name: run notice:ruby:verify
        run: |
            bin/rails notice:ruby:verify
      - name: output the branch
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        run: | 
          echo ${{ github.ref }} > branch.txt
      - name: save branch to build
        if: ${{ failure() && github.actor == 'dependabot[bot]' }}
        uses: actions/upload-artifact@v2
        with:
          name: branch_to_update
          path: branch.txt

